### ISSUE TITLE
Will not start after installing on Mac.

### ISSUE THREAD

**Issue by thegreystone** [BCN3D/BCN3D-Cura-Mac#1]
Tried installing on Mac OS X 10.11.3. After selecting Sigma as my printer, it crashes with Cura-BCN3D Error.

The log says:
2016-01-26 21:25:26,372 Cura-BCN3D[15593]: GLUT Warning: glutInit being called a second time.
2016-01-26 21:25:26,373 Cura-BCN3D[15593]: 2016-01-26 21:25:26.372 Cura-BCN3D[15593:2010570] GLUT Warning: glutInit being called a second time.
2016-01-26 21:25:26,416 Cura-BCN3D[15593]: La version que tengo ahora es: 0.1.2
2016-01-26 21:25:26,649 Cura-BCN3D[15593]: Traceback (most recent call last):
2016-01-26 21:25:26,649 Cura-BCN3D[15593]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/**boot**.py", line 351, in <module>
2016-01-26 21:25:26,649 Cura-BCN3D[15593]:     _run()
2016-01-26 21:25:26,649 Cura-BCN3D[15593]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/__boot__.py", line 336, in _run
2016-01-26 21:25:26,649 Cura-BCN3D[15593]:     exec(compile(source, path, 'exec'), globals(), globals())
2016-01-26 21:25:26,649 Cura-BCN3D[15593]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/cura.py", line 89, in <module>
2016-01-26 21:25:26,649 Cura-BCN3D[15593]:     main()
2016-01-26 21:25:26,649 Cura-BCN3D[15593]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/cura.py", line 86, in main
2016-01-26 21:25:26,649 Cura-BCN3D[15593]:     app.CuraApp(args).MainLoop()
2016-01-26 21:25:26,650 Cura-BCN3D[15593]:   File "Cura/gui/app.pyo", line 58, in __init__
2016-01-26 21:25:26,650 Cura-BCN3D[15593]:   File "Cura/gui/app.pyo", line 140, in afterSplashCallback
2016-01-26 21:25:26,650 Cura-BCN3D[15593]:   File "Cura/util/version.pyo", line 238, in checkForNewVersion
2016-01-26 21:25:26,650 Cura-BCN3D[15593]:   File "urllib2.pyo", line 154, in urlopen
2016-01-26 21:25:26,650 Cura-BCN3D[15593]:   File "urllib2.pyo", line 431, in open
2016-01-26 21:25:26,650 Cura-BCN3D[15593]:   File "urllib2.pyo", line 449, in _open
2016-01-26 21:25:26,650 Cura-BCN3D[15593]:   File "urllib2.pyo", line 409, in _call_chain
2016-01-26 21:25:26,650 Cura-BCN3D[15593]:   File "urllib2.pyo", line 1240, in https_open
2016-01-26 21:25:26,650 Cura-BCN3D[15593]:   File "urllib2.pyo", line 1197, in do_open
2016-01-26 21:25:26,650 Cura-BCN3D[15593]: urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
2016-01-26 21:25:26,716 Cura-BCN3D[15593]: Cura-BCN3D Error
2016-01-26 21:25:26,716 Cura-BCN3D[15593]: 2016-01-26 21:25:26.715 Cura-BCN3D[15593:2010570] Cura-BCN3D Error

**Comment by remelbourne** [comment]
I will take a look at it and get back to you as soon as possible.

**Comment by remelbourne** [comment]
From the code that you gave it seems to be a problem with the automatic check for a new version. I made some changes to the code, and it works on my laptop. Let me know whether you still experience the same problem or if a new one comes up.

**Comment by flandaluce** [comment]
Tengo el mismo problema al instalar la nueva versión.
He probado un update con el anterior instalado
A continuación he eliminado toda la instalación antigua con AppCleaner y he ejecutado una nueva instalación.
Dio el aviso de falta de certificación de apple, le di la autorización, lo instalo correctamente, pero igual aparece el problema y no quiere funcionar-
Los errores en el log han sido los mismos en las dos ocasiones

28/01/16 2:34:59.998 p.m. appleeventsd[58]: SecTaskLoadEntitlements failed error=22
28/01/16 2:35:00.002 p.m. launchservicesd[84]: SecTaskLoadEntitlements failed error=22
28/01/16 2:35:00.006 p.m. launchservicesd[84]: SecTaskLoadEntitlements failed error=22
28/01/16 2:35:03.708 p.m. Cura-BCN3D[97756]: GLUT Warning: glutInit being called a second time.
28/01/16 2:35:03.708 p.m. Cura-BCN3D[97756]: 2016-01-28 14:35:03.707 Cura-BCN3D[97756:2619477] GLUT Warning: glutInit being called a second time.
28/01/16 2:35:03.743 p.m. Cura-BCN3D[97756]: La version que tengo ahora es: 0.1.3
28/01/16 2:35:04.518 p.m. Cura-BCN3D[97756]: Traceback (most recent call last):
28/01/16 2:35:04.518 p.m. Cura-BCN3D[97756]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/**boot**.py", line 351, in <module>
28/01/16 2:35:04.518 p.m. Cura-BCN3D[97756]:     _run()
28/01/16 2:35:04.518 p.m. Cura-BCN3D[97756]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/__boot__.py", line 336, in _run
28/01/16 2:35:04.518 p.m. Cura-BCN3D[97756]:     exec(compile(source, path, 'exec'), globals(), globals())
28/01/16 2:35:04.519 p.m. Cura-BCN3D[97756]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/cura.py", line 89, in <module>
28/01/16 2:35:04.519 p.m. Cura-BCN3D[97756]:     main()
28/01/16 2:35:04.519 p.m. Cura-BCN3D[97756]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/cura.py", line 86, in main
28/01/16 2:35:04.519 p.m. Cura-BCN3D[97756]:     app.CuraApp(args).MainLoop()
28/01/16 2:35:04.519 p.m. Cura-BCN3D[97756]:   File "Cura/gui/app.pyo", line 58, in __init__
28/01/16 2:35:04.519 p.m. Cura-BCN3D[97756]:   File "Cura/gui/app.pyo", line 140, in afterSplashCallback
28/01/16 2:35:04.519 p.m. Cura-BCN3D[97756]:   File "Cura/util/version.pyo", line 255, in checkForNewVersion
28/01/16 2:35:04.519 p.m. Cura-BCN3D[97756]:   File "urllib2.pyo", line 154, in urlopen
28/01/16 2:35:04.519 p.m. Cura-BCN3D[97756]:   File "urllib2.pyo", line 431, in open
28/01/16 2:35:04.519 p.m. Cura-BCN3D[97756]:   File "urllib2.pyo", line 449, in _open
28/01/16 2:35:04.519 p.m. Cura-BCN3D[97756]:   File "urllib2.pyo", line 409, in _call_chain
28/01/16 2:35:04.519 p.m. Cura-BCN3D[97756]:   File "urllib2.pyo", line 1240, in https_open
28/01/16 2:35:04.519 p.m. Cura-BCN3D[97756]:   File "urllib2.pyo", line 1197, in do_open
28/01/16 2:35:04.519 p.m. Cura-BCN3D[97756]: urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
28/01/16 2:35:04.586 p.m. Cura-BCN3D[97756]: Cura-BCN3D Error
28/01/16 2:35:04.586 p.m. Cura-BCN3D[97756]: 2016-01-28 14:35:04.585 Cura-BCN3D[97756:2619477] Cura-BCN3D Error

**Comment by thegreystone** [comment]
I tried the 0.1.3 version and got this:
2016-01-29 08:26:41,000 kernel[0]: hfs: mounted Cura - Ultimaker on device disk2s9
2016-01-29 08:26:41,039 mds[61]: (Volume.Normal:2464) volume:0x7f838988ae00 *********\* Bootstrapped Creating a default store:1 SpotLoc:(null) SpotVerLoc:(null) occlude:0 /Volumes/Cura - Ultimaker
2016-01-29 08:27:06,459 Cura-BCN3D[8384]: GLUT Warning: glutInit being called a second time.
2016-01-29 08:27:06,459 Cura-BCN3D[8384]: 2016-01-29 08:27:06.458 Cura-BCN3D[8384:2486642] GLUT Warning: glutInit being called a second time.
2016-01-29 08:27:06,519 Cura-BCN3D[8384]: Loading old settings from /Users/marcus/Library/Application Support/Cura/0.1.2
2016-01-29 08:27:06,530 Cura-BCN3D[8384]: La version que tengo ahora es: 0.1.3
2016-01-29 08:27:06,784 Cura-BCN3D[8384]: Traceback (most recent call last):
2016-01-29 08:27:06,784 Cura-BCN3D[8384]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/**boot**.py", line 351, in <module>
2016-01-29 08:27:06,784 Cura-BCN3D[8384]:     _run()
2016-01-29 08:27:06,784 Cura-BCN3D[8384]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/__boot__.py", line 336, in _run
2016-01-29 08:27:06,784 Cura-BCN3D[8384]:     exec(compile(source, path, 'exec'), globals(), globals())
2016-01-29 08:27:06,784 Cura-BCN3D[8384]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/cura.py", line 89, in <module>
2016-01-29 08:27:06,784 Cura-BCN3D[8384]:     main()
2016-01-29 08:27:06,784 Cura-BCN3D[8384]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/cura.py", line 86, in main
2016-01-29 08:27:06,784 Cura-BCN3D[8384]:     app.CuraApp(args).MainLoop()
2016-01-29 08:27:06,784 Cura-BCN3D[8384]:   File "Cura/gui/app.pyo", line 58, in __init__
2016-01-29 08:27:06,784 Cura-BCN3D[8384]:   File "Cura/gui/app.pyo", line 140, in afterSplashCallback
2016-01-29 08:27:06,784 Cura-BCN3D[8384]:   File "Cura/util/version.pyo", line 255, in checkForNewVersion
2016-01-29 08:27:06,784 Cura-BCN3D[8384]:   File "urllib2.pyo", line 154, in urlopen
2016-01-29 08:27:06,784 Cura-BCN3D[8384]:   File "urllib2.pyo", line 431, in open
2016-01-29 08:27:06,784 Cura-BCN3D[8384]:   File "urllib2.pyo", line 449, in _open
2016-01-29 08:27:06,785 Cura-BCN3D[8384]:   File "urllib2.pyo", line 409, in _call_chain
2016-01-29 08:27:06,785 Cura-BCN3D[8384]:   File "urllib2.pyo", line 1240, in https_open
2016-01-29 08:27:06,785 Cura-BCN3D[8384]:   File "urllib2.pyo", line 1197, in do_open
2016-01-29 08:27:06,785 Cura-BCN3D[8384]: urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
2016-01-29 08:27:06,851 Cura-BCN3D[8384]: Cura-BCN3D Error
2016-01-29 08:27:06,851 Cura-BCN3D[8384]: 2016-01-29 08:27:06.851 Cura-BCN3D[8384:2486642] Cura-BCN3D Error

**Comment by rabieau79** [comment]
Hi,
I have the same problem.
Cura-BCN3D Error when I launch Cura
No solution ?

**Comment by denisvic** [comment]
Same error for me. Impossible to launch CURA

It looks like a certificate error : `17/02/2016 22:17:42,350 Cura-BCN3D[1662]: urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>`

```
17/02/2016 22:17:42,060 Cura-BCN3D[1662]: La version que tengo ahora es: 0.1.3
17/02/2016 22:17:42,349 Cura-BCN3D[1662]: Traceback (most recent call last):
17/02/2016 22:17:42,349 Cura-BCN3D[1662]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/__boot__.py", line 351, in <module>
17/02/2016 22:17:42,349 Cura-BCN3D[1662]:     _run()
17/02/2016 22:17:42,349 Cura-BCN3D[1662]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/__boot__.py", line 336, in _run
17/02/2016 22:17:42,349 Cura-BCN3D[1662]:     exec(compile(source, path, 'exec'), globals(), globals())
17/02/2016 22:17:42,349 Cura-BCN3D[1662]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/cura.py", line 89, in <module>
17/02/2016 22:17:42,349 Cura-BCN3D[1662]:     main()
17/02/2016 22:17:42,349 Cura-BCN3D[1662]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/cura.py", line 86, in main
17/02/2016 22:17:42,349 Cura-BCN3D[1662]:     app.CuraApp(args).MainLoop()
17/02/2016 22:17:42,349 Cura-BCN3D[1662]:   File "Cura/gui/app.pyo", line 58, in __init__
17/02/2016 22:17:42,349 Cura-BCN3D[1662]:   File "Cura/gui/app.pyo", line 140, in afterSplashCallback
17/02/2016 22:17:42,349 Cura-BCN3D[1662]:   File "Cura/util/version.pyo", line 255, in checkForNewVersion
17/02/2016 22:17:42,349 Cura-BCN3D[1662]:   File "urllib2.pyo", line 154, in urlopen
17/02/2016 22:17:42,349 Cura-BCN3D[1662]:   File "urllib2.pyo", line 431, in open
17/02/2016 22:17:42,350 Cura-BCN3D[1662]:   File "urllib2.pyo", line 449, in _open
17/02/2016 22:17:42,350 Cura-BCN3D[1662]:   File "urllib2.pyo", line 409, in _call_chain
17/02/2016 22:17:42,350 Cura-BCN3D[1662]:   File "urllib2.pyo", line 1240, in https_open
17/02/2016 22:17:42,350 Cura-BCN3D[1662]:   File "urllib2.pyo", line 1197, in do_open
17/02/2016 22:17:42,350 Cura-BCN3D[1662]: urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
17/02/2016 22:17:42,357 Cura-BCN3D[1662]: Cura-BCN3D Error
17/02/2016 22:17:42,358 Cura-BCN3D[1662]: 2016-02-17 22:17:42.357 Cura-BCN3D[1662:274764] Cura-BCN3D Error

```

**Comment by kitusmark** [comment]
I've been able to launch Cura for my Mac running 10.11.3 without any problems. 

<img width="1588" alt="captura de pantalla 2016-02-22 a las 16 34 22" src="https://cloud.githubusercontent.com/assets/6075056/13224683/f7c4deb0-d989-11e5-86dc-aa715735b77e.png">

As your logs says it seems to be problems with the code that checks for updates. Remember you need internet connection when launching the Software.

Also, before installing the new version, make sure to uninstall previous versions with some software tool like appcleaner. 

We'll be doing more tests and come back to you as soon as posible

**Comment by kitusmark** [comment]
I've tried to launch Cura without internet connection and the error shows up. Make sure to have internet and try again. 
<img width="532" alt="captura de pantalla 2016-02-22 a las 17 37 55" src="https://cloud.githubusercontent.com/assets/6075056/13225039/6f371642-d98b-11e5-96e5-d5b827a2867d.png">

<img width="1448" alt="captura de pantalla 2016-02-22 a las 17 37 42" src="https://cloud.githubusercontent.com/assets/6075056/13225060/842c0080-d98b-11e5-93d5-ead7756e281e.png">

We'll update the code and see what occurs.

Thanks for your patience

**Comment by thegreystone** [comment]
I’m connected to the internet but I get the same thing.

/M

**Comment by denisvic** [comment]
Hi Marc,
Error is not the same. I confirm you that I've an Internet connection when I launch Cura.
I previously used Cura for Ultimaker but uninstalled it before installing Cura for BCN3D.
Best regards,

----Denis VICTORIA

Date: Mon, 22 Feb 2016 08:41:48 -0800

**Comment by rskproductions** [comment]
Tinc el mateix problema. No arranca.

**Comment by rskproductions** [comment]
23/2/16 11:33:40,652 Cura-BCN3D[12240]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/**boot**.py", line 336, in _run
23/2/16 11:33:40,652 Cura-BCN3D[12240]:     exec(compile(source, path, 'exec'), globals(), globals())
23/2/16 11:33:40,653 Cura-BCN3D[12240]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/cura.py", line 89, in <module>
23/2/16 11:33:40,653 Cura-BCN3D[12240]:     main()
23/2/16 11:33:40,653 Cura-BCN3D[12240]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/cura.py", line 86, in main
23/2/16 11:33:40,654 Cura-BCN3D[12240]:     app.CuraApp(args).MainLoop()
23/2/16 11:33:40,654 Cura-BCN3D[12240]:   File "Cura/gui/app.pyo", line 58, in __init__
23/2/16 11:33:40,654 Cura-BCN3D[12240]:   File "Cura/gui/app.pyo", line 140, in afterSplashCallback
23/2/16 11:33:40,654 Cura-BCN3D[12240]:   File "Cura/util/version.pyo", line 255, in checkForNewVersion
23/2/16 11:33:40,655 Cura-BCN3D[12240]:   File "urllib2.pyo", line 154, in urlopen
23/2/16 11:33:40,655 Cura-BCN3D[12240]:   File "urllib2.pyo", line 431, in open
23/2/16 11:33:40,655 Cura-BCN3D[12240]:   File "urllib2.pyo", line 449, in _open
23/2/16 11:33:40,655 Cura-BCN3D[12240]:   File "urllib2.pyo", line 409, in _call_chain
23/2/16 11:33:40,655 Cura-BCN3D[12240]:   File "urllib2.pyo", line 1240, in https_open
23/2/16 11:33:40,655 Cura-BCN3D[12240]:   File "urllib2.pyo", line 1197, in do_open
23/2/16 11:33:40,655 Cura-BCN3D[12240]: urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
....

**Comment by JavierBurg** [comment]
Same problem here... 

OSX version: 10.9.5, MacBookPro 
Cura-BCN3D 0.1.3
What can I do to help? May I compile a version here?
Ive seen that this error appears in other Python soft...

25/02/16 22:32:20,489 Cura-BCN3D[12293]: GLUT Warning: glutInit being called a second time.
25/02/16 22:32:20,489 Cura-BCN3D[12293]: 2016-02-25 22:32:20.488 Cura-BCN3D[12293:707] GLUT Warning: glutInit being called a second time.
25/02/16 22:32:20,581 Cura-BCN3D[12293]: La version que tengo ahora es: 0.1.3
25/02/16 22:32:20,928 Cura-BCN3D[12293]: Traceback (most recent call last):
25/02/16 22:32:20,929 Cura-BCN3D[12293]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/**boot**.py", line 351, in <module>
25/02/16 22:32:20,929 Cura-BCN3D[12293]:     _run()
25/02/16 22:32:20,929 Cura-BCN3D[12293]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/__boot__.py", line 336, in _run
25/02/16 22:32:20,929 Cura-BCN3D[12293]:     exec(compile(source, path, 'exec'), globals(), globals())
25/02/16 22:32:20,929 Cura-BCN3D[12293]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/cura.py", line 89, in <module>
25/02/16 22:32:20,930 Cura-BCN3D[12293]:     main()
25/02/16 22:32:20,930 Cura-BCN3D[12293]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/cura.py", line 86, in main
25/02/16 22:32:20,930 Cura-BCN3D[12293]:     app.CuraApp(args).MainLoop()
25/02/16 22:32:20,930 Cura-BCN3D[12293]:   File "Cura/gui/app.pyo", line 58, in __init__
25/02/16 22:32:20,930 Cura-BCN3D[12293]:   File "Cura/gui/app.pyo", line 140, in afterSplashCallback
25/02/16 22:32:20,931 Cura-BCN3D[12293]:   File "Cura/util/version.pyo", line 255, in checkForNewVersion
25/02/16 22:32:20,931 Cura-BCN3D[12293]:   File "urllib2.pyo", line 154, in urlopen
25/02/16 22:32:20,931 Cura-BCN3D[12293]:   File "urllib2.pyo", line 431, in open
25/02/16 22:32:20,931 Cura-BCN3D[12293]:   File "urllib2.pyo", line 449, in _open
25/02/16 22:32:20,931 Cura-BCN3D[12293]:   File "urllib2.pyo", line 409, in _call_chain
25/02/16 22:32:20,931 Cura-BCN3D[12293]:   File "urllib2.pyo", line 1240, in https_open
25/02/16 22:32:20,931 Cura-BCN3D[12293]:   File "urllib2.pyo", line 1197, in do_open
25/02/16 22:32:20,931 Cura-BCN3D[12293]: urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
25/02/16 22:32:20,996 Cura-BCN3D[12293]: Cura-BCN3D Error
25/02/16 22:32:20,996 Cura-BCN3D[12293]: 2016-02-25 22:32:20.995 Cura-BCN3D[12293:707] Cura-BCN3D Error
25/02/16 22:32:23,693 com.apple.launchd.peruser.501[360]: (com.ultimaker.Cura-BCN3D0.1.3.158960[12293]) Exited with code: 255

**Comment by denisvic** [comment]
Some updates about this problem ?

**Comment by lukey12321** [comment]
Hey everyone,

I too have problems when opening cura.  I attached a log of the error message

Any help much appreciated! :)

[error message.pdf](https://github.com/BCN3D/BCN3D-Cura-Mac/files/197928/error.message.pdf)

**Comment by remelbourne** [comment]
It has been fixed in version 0.1.4, thank you all.

**Comment by thegreystone** [comment]
Confirmed. Now starts up fine for me.

**Comment by lukey12321** [comment]
Working for me now too :) Thanks!!!
